---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/benoitlx/niri

name: niri 
description: personnal niri based image
base-image: ghcr.io/ublue-os/base-main
image-version: latest

stages:
  - name: ironbar
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - apt-get update && apt-get install -y git build-essential libgtk-3-dev libgtk-layer-shell-dev libssl-dev libdbusmenu-gtk3-dev libpulse-dev libinput-dev lua-lgi libluajit2-5.1-dev
          - git clone https://github.com/jakestanger/ironbar.git
          - cd ironbar && RUSTFLAGS="-C target-feature=-crt-static" cargo build --release
          - mkdir -p /out/ && mv /ironbar/target/release/ironbar /out/ironbar
  - name: matugen
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - apt-get update && apt-get install -y git
          - git clone https://github.com/InioX/matugen
          - cd matugen && RUSTFLAGS="-C target-feature=-crt-static" cargo build --release
          - mkdir -p /out/ && mv /matugen/target/release/matugen /out/matugen

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: copy
    from: ironbar # rust
    src: /out/ironbar
    dest: /usr/bin/

  - type: copy
    from: matugen # rust
    src: /out/matugen
    dest: /usr/bin/

  - type: dnf 
    repos:
      copr:
        - yalter/niri # packaged by the maintainer
        - atim/starship
        - lihaohong/yazi
        - varlad/zellij 
        - alebastr/sway-extras # swww seems up to date here
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        # TODO add keys
    install:
      packages:
        # DE
        - niri # rust
        - polkit
        - pavucontrol
        - rofi
        # portal
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - xwayland-satellite
        - gnome-keyring
        - swww

        # Term emulator
        - kitty

        # editors
        - vim
        - helix # rust

        # term bling
        - btop 
        - starship # rust
        - fastfetch
        - lolcat
        - cava
        - cowsay
        - yazi # rust
        - zellij # rust

        # Misc
        - tailscale
        - syncthing
        - rsync
        - luajit # lua jit compiler for ironbar Can remove this by disabling the feature during the build

        # dev
        - gcc
    remove:
      packages:
        - alacritty
        - htop
        - waybar
        - firefox
        - fuzzel

  - type: fonts
    fonts:
      nerd-fonts:
        - IBMPlexMono
        - FiraCode
      google-fonts:
        - Dancing Script
        - Pacifico
        - Lobster
        - Caveat
        - Twinkle Star

  - type: chezmoi
    repository: "https://github.com/benoitlx/dotfiles"
    wait-after-boot: "1m"

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (base)"
      install:
        - org.mozilla.firefox
        - com.discordapp.Discord
        - org.videolan.VLC
        - org.mozilla.Thunderbird
        - com.rtosta.zapzap

  - type: signing
