# image will be published to ghcr.io/benoitlx/<name>
name: custom-hyprland-nvidia 
description: This is my personal OS image including hyprland and nvidia driver.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-nvidia
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: hyprland-rpm.yml

  - type: files
    files:
      - hyprland/usr: /usr

  - from-file: base-rpm-packages.yml
  - from-file: base-flatpak-packages.yml

  - from-file: chezmoi.yml

  - type: fonts
    fonts:
      nerd-fonts:
        - IBMPlexMono 
        - FiraCode
        - Hack
        - JetBrainsMono
