---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/benoitlx/niri

name: niri 
description: personnal niri based image
base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf 
    repos:
      copr:
        - yalter/niri
        - victorvintorez/tilingtools
        - atim/starship 
        - lihaohong/yazi
        - varlad/zellij 
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      packages:
        # DE
        - ironbar # rust
        - niri # rust
        - polkit
        - dunst
        - pavucontrol
        # portal
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring

        # Term emulator
        - kitty

        # editors
        - vim
        - helix # rust

        # term bling
        - btop 
        - starship
        - fastfetch
        - lolcat
        - cava
        - cowsay
        - yazi
        - zellij

        # Misc background
        - tailscale
        - syncthing
        - rsync

        # dev
        - gcc
    remove:
      packages:
        - alacritty
        - htop
        - waybar

  - type: fonts
    fonts:
      nerd-fonts:
        - IBMPlexMono
        - FiraCode

  - type: chezmoi
    repository: "https://github.com/benoitlx/dotfiles"
    wait-after-boot: "1m"

# TODO
# - remove unecessary flatpak
      

  - type: signing
