---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/benoitlx/niri

name: niri 
description: personnal niri based image
base-image: ghcr.io/ublue-os/base-main
image-version: latest

stages:
  - name: ironbar
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - apt-get update && apt-get install -y git build-essential libgtk-3-dev libgtk-layer-shell-dev libssl-dev libdbusmenu-gtk3-dev libpulse-dev libinput-dev lua-lgi libluajit-5.1-dev
          - git clone https://github.com/jakestanger/ironbar.git
          - cd ironbar && RUSTFLAGS="-C target-feature=-crt-static" cargo build --release
          - mkdir -p /out/ && mv /ironbar/target/release/ironbar /out/ironbar
  - name: matugen
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - apt-get update && apt-get install -y git
          - git clone https://github.com/InioX/matugen
          - cd matugen && RUSTFLAGS="-C target-feature=-crt-static" cargo build --release
          - mkdir -p /out/ && mv /matugen/target/release/matugen /out/matugen

modules:
  - from-file: common.yml
