---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/benoitlx/niri

name: niri 
description: personnal niri based image
base-image: ghcr.io/ublue-os/base-main
image-version: latest

stages:
  - from-file: shared-stages.yml

modules:
  - from-file: common.yml
