# image will be published to ghcr.io/benoitlx/custom-hyprland-nvidia
name: custom-hyprland-nvidia 
description: This is my personal OS image including hyprland and nvidia driver.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-nvidia
image-version: latest # latest is also supported if you want new updates ASAP
stages:
  - name: ly
    from: docker.io/library/debian
    modules:
      - type: script
        scripts:
          - ly-debian-install.sh

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: hyprland-nvidia/hyprland-rpm.yml
  - from-file: hyprland-nvidia/copr-hyprland.yml
  - from-file: hyprland-nvidia/hyprland-files.yml
  - from-file: hyprland-nvidia/hyprland-scripts.yml

  - from-file: hyprland-nvidia/base-rpm-packages.yml
  - from-file: hyprland-nvidia/base-flatpak-packages.yml

  - from-file: hyprland-nvidia/chezmoi.yml
  - from-file: hyprland-nvidia/fonts.yml

  - from-file: hyprland-nvidia/ly-files.yml

  - from-file: hyprland-nvidia/common-files.yml
  - type: script
    snippets:
      - chmod +x /usr/etc/ly-workaround/ly-workaround

  - from-file: hyprland-nvidia/systemd.yml
