---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/benoitlx/niri

name: niri 
description: personnal niri based image
base-image: ghcr.io/ublue-os/base-main
image-version: latest

stages:
  - name: ironbar
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - apt-get update && apt-get install -y git build-essential libgtk-3-dev libgtk-layer-shell-dev libssl-dev libdbusmenu-gtk3-dev libpulse-dev libinput-dev lua-lgi libluajit2-5.1-dev
          - git clone https://github.com/jakestanger/ironbar.git
          - cd ironbar && RUSTFLAGS="-C target-feature=-crt-static" cargo build --release
          - mkdir -p /out/ && mv /ironbar/target/release/ironbar /out/ironbar

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: copy
    from: ironbar
    src: /out/ironbar
    dest: /usr/bin/

  - type: dnf 
    repos:
      copr:
        - yalter/niri
        - atim/starship 
        - lihaohong/yazi
        - varlad/zellij 
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      packages:
        # DE
        - niri # rust
        - polkit
        - dunst
        - pavucontrol
        # portal
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring

        # Term emulator
        - kitty

        # editors
        - vim
        - helix # rust

        # term bling
        - btop 
        - starship
        - fastfetch
        - lolcat
        - cava
        - cowsay
        - yazi
        - zellij

        # Misc
        - tailscale
        - syncthing
        - rsync
        - luajit # lua jit compiler for ironbar Can remove this by disabling the feature during the build

        # dev
        - gcc
    remove:
      packages:
        - alacritty
        - htop
        - waybar

  - type: fonts
    fonts:
      nerd-fonts:
        - IBMPlexMono
        - FiraCode

  - type: chezmoi
    repository: "https://github.com/benoitlx/dotfiles"
    wait-after-boot: "1m"

# TODO
# - remove unecessary flatpak
      

  - type: signing
